血糖子系统前端界面初步实现
SEMedical/Frontend pull request #5
Opened 2023-12-30 16:03 UTC by Karry-Angel

血糖子系统的前端大致写完啦！还存在几个后续待修改的问题：
1.“<”“>”按钮切换日期，是否要保留？因为就现在来看，他会让曲线图变得很小，页面不太美观，而且实现的逻辑较复杂
2.待后端更改了获取实时血糖小贴士的接口后，指添加颜色的返回值后，再更改一下bloodSugarCalendarGraphic和bloodSugarCalendarText页面的血糖贴士部分，及贴士的接口api文件

2023-12-30 16:52 UTC, VictorHuu commented
太震撼了 👍

2024-01-01 11:59 UTC, DaenerysTar approved these changes
OK

2024-01-02 07:17 UTC, VictorHuu commented on utils/request.js
git pull origin zap1230 --rebase

2024-01-02 13:22 UTC, VictorHuu requested changes
血糖数据返回成功，修改运动部分

2024-01-02 13:22 UTC, VictorHuu commented on pages/index/bloodSugarCalendarGraphic.vue
> +			   //获取运动数据
修改map逻辑，处理JSON的map数据

2024-01-03 09:52 UTC, VictorHuu requested changes
修改map数据的处理方式

2024-01-03 10:04 UTC, VictorHuu approved these changes

2024-01-03 10:05 UTC, VictorHuu requested changes
...

2024-01-03 10:34 UTC, VictorHuu approved these changes

2024-01-03 10:35 UTC, merged